/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125rootLayoutRouteRouteImport } from './routes/{-$locale}/(root-layout)/route'
import { Route as Char123LocaleChar125centeredLayoutRouteRouteImport } from './routes/{-$locale}/(centered-layout)/route'
import { Route as Char123LocaleChar125rootLayoutIndexRouteImport } from './routes/{-$locale}/(root-layout)/index'
import { Route as ApiHealthLiveRouteImport } from './routes/[_]api/health/live'
import { Route as Char123LocaleChar125rootLayoutauthRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/route'
import { Route as Char123LocaleChar125centeredLayoutguestRouteRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/route'
import { Route as Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport } from './routes/{-$locale}/(root-layout)/terms-of-service/index'
import { Route as Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport } from './routes/{-$locale}/(root-layout)/privacy-policy/index'
import { Route as Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport } from './routes/{-$locale}/(root-layout)/playground/index'
import { Route as Char123LocaleChar125rootLayoutErrorIndexRouteImport } from './routes/{-$locale}/(root-layout)/error/index'
import { Route as Char123LocaleChar125centeredLayoutAcceptInvitationIndexRouteImport } from './routes/{-$locale}/(centered-layout)/accept-invitation/index'
import { Route as Char123LocaleChar125rootLayoutauthDashboardRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/dashboard/route'
import { Route as Char123LocaleChar125rootLayoutauthAdminRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/admin/route'
import { Route as Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/dashboard/index'
import { Route as Char123LocaleChar125rootLayoutauthAdminIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/admin/index'
import { Route as Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/sign-in/index'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/route'
import { Route as Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/admin/organizations/index'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/route'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/route'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/index'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/index'
import { Route as Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/admin/organizations/$organizationSlug/index'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/$productSlug/index'
import { Route as Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/members/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125rootLayoutRouteRoute =
  Char123LocaleChar125rootLayoutRouteRouteImport.update({
    id: '/(root-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutRouteRoute =
  Char123LocaleChar125centeredLayoutRouteRouteImport.update({
    id: '/(centered-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutIndexRoute =
  Char123LocaleChar125rootLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/_api/health/live',
  path: '/_api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125rootLayoutauthRouteRoute =
  Char123LocaleChar125rootLayoutauthRouteRouteImport.update({
    id: '/(auth)',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestRouteRoute =
  Char123LocaleChar125centeredLayoutguestRouteRouteImport.update({
    id: '/(guest)',
    getParentRoute: () => Char123LocaleChar125centeredLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute =
  Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute =
  Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPlaygroundIndexRoute =
  Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport.update({
    id: '/playground/',
    path: '/playground/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutErrorIndexRoute =
  Char123LocaleChar125rootLayoutErrorIndexRouteImport.update({
    id: '/error/',
    path: '/error/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute =
  Char123LocaleChar125centeredLayoutAcceptInvitationIndexRouteImport.update({
    id: '/accept-invitation/',
    path: '/accept-invitation/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthDashboardRouteRoute =
  Char123LocaleChar125rootLayoutauthDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthAdminRouteRoute =
  Char123LocaleChar125rootLayoutauthAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthDashboardIndexRoute =
  Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthDashboardRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthAdminIndexRoute =
  Char123LocaleChar125rootLayoutauthAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthAdminRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestSignInIndexRoute =
  Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport.update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteImport.update({
    id: '/org/$organizationSlug',
    path: '/org/$organizationSlug',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute =
  Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthAdminRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteImport.update(
    {
      id: '/catalog',
      path: '/catalog',
      getParentRoute: () =>
        Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute,
    } as any,
  )
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteImport.update(
    {
      id: '/(workspace)',
      getParentRoute: () =>
        Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute,
    } as any,
  )
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute,
    } as any,
  )
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute,
    } as any,
  )
const Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute =
  Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRouteImport.update(
    {
      id: '/organizations/$organizationSlug/',
      path: '/organizations/$organizationSlug/',
      getParentRoute: () => Char123LocaleChar125rootLayoutauthAdminRouteRoute,
    } as any,
  )
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRouteImport.update(
    {
      id: '/$productSlug/',
      path: '/$productSlug/',
      getParentRoute: () =>
        Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute,
    } as any,
  )
const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRouteImport.update(
    {
      id: '/members/',
      path: '/members/',
      getParentRoute: () =>
        Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125rootLayoutauthAdminRouteRouteWithChildren
  '/{-$locale}/dashboard': typeof Char123LocaleChar125rootLayoutauthDashboardRouteRouteWithChildren
  '/{-$locale}/accept-invitation/': typeof Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute
  '/{-$locale}/error/': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/playground/': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/privacy-policy/': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/terms-of-service/': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/org/$organizationSlug': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteWithChildren
  '/{-$locale}/sign-in/': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125rootLayoutauthAdminIndexRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  '/{-$locale}/org/$organizationSlug/catalog': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteWithChildren
  '/{-$locale}/admin/organizations/': typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute
  '/{-$locale}/admin/organizations/$organizationSlug/': typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute
  '/{-$locale}/org/$organizationSlug/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute
  '/{-$locale}/org/$organizationSlug/catalog/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute
  '/{-$locale}/org/$organizationSlug/members/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute
  '/{-$locale}/org/$organizationSlug/catalog/$productSlug/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/accept-invitation': typeof Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute
  '/{-$locale}/error': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/org/$organizationSlug': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125rootLayoutauthAdminIndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  '/{-$locale}/admin/organizations': typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute
  '/{-$locale}/admin/organizations/$organizationSlug': typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute
  '/{-$locale}/org/$organizationSlug/catalog': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute
  '/{-$locale}/org/$organizationSlug/members': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute
  '/{-$locale}/org/$organizationSlug/catalog/$productSlug': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/(centered-layout)': typeof Char123LocaleChar125centeredLayoutRouteRouteWithChildren
  '/{-$locale}/(root-layout)': typeof Char123LocaleChar125rootLayoutRouteRouteWithChildren
  '/{-$locale}/(centered-layout)/(guest)': typeof Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren
  '/{-$locale}/(root-layout)/(auth)': typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/(root-layout)/': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/{-$locale}/(root-layout)/(auth)/admin': typeof Char123LocaleChar125rootLayoutauthAdminRouteRouteWithChildren
  '/{-$locale}/(root-layout)/(auth)/dashboard': typeof Char123LocaleChar125rootLayoutauthDashboardRouteRouteWithChildren
  '/{-$locale}/(centered-layout)/accept-invitation/': typeof Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute
  '/{-$locale}/(root-layout)/error/': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/(root-layout)/playground/': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/(root-layout)/privacy-policy/': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/(root-layout)/terms-of-service/': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteWithChildren
  '/{-$locale}/(centered-layout)/(guest)/sign-in/': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/(root-layout)/(auth)/admin/': typeof Char123LocaleChar125rootLayoutauthAdminIndexRoute
  '/{-$locale}/(root-layout)/(auth)/dashboard/': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteWithChildren
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteWithChildren
  '/{-$locale}/(root-layout)/(auth)/admin/organizations/': typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute
  '/{-$locale}/(root-layout)/(auth)/admin/organizations/$organizationSlug/': typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/members/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute
  '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/$productSlug/': typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_api/health/live'
    | '/{-$locale}/'
    | '/{-$locale}/admin'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/accept-invitation/'
    | '/{-$locale}/error/'
    | '/{-$locale}/playground/'
    | '/{-$locale}/privacy-policy/'
    | '/{-$locale}/terms-of-service/'
    | '/{-$locale}/org/$organizationSlug'
    | '/{-$locale}/sign-in/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/org/$organizationSlug/catalog'
    | '/{-$locale}/admin/organizations/'
    | '/{-$locale}/admin/organizations/$organizationSlug/'
    | '/{-$locale}/org/$organizationSlug/'
    | '/{-$locale}/org/$organizationSlug/catalog/'
    | '/{-$locale}/org/$organizationSlug/members/'
    | '/{-$locale}/org/$organizationSlug/catalog/$productSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_api/health/live'
    | '/{-$locale}/accept-invitation'
    | '/{-$locale}/error'
    | '/{-$locale}/playground'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/org/$organizationSlug'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/admin'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/admin/organizations'
    | '/{-$locale}/admin/organizations/$organizationSlug'
    | '/{-$locale}/org/$organizationSlug/catalog'
    | '/{-$locale}/org/$organizationSlug/members'
    | '/{-$locale}/org/$organizationSlug/catalog/$productSlug'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/(centered-layout)'
    | '/{-$locale}/(root-layout)'
    | '/{-$locale}/(centered-layout)/(guest)'
    | '/{-$locale}/(root-layout)/(auth)'
    | '/_api/health/live'
    | '/{-$locale}/(root-layout)/'
    | '/{-$locale}/(root-layout)/(auth)/admin'
    | '/{-$locale}/(root-layout)/(auth)/dashboard'
    | '/{-$locale}/(centered-layout)/accept-invitation/'
    | '/{-$locale}/(root-layout)/error/'
    | '/{-$locale}/(root-layout)/playground/'
    | '/{-$locale}/(root-layout)/privacy-policy/'
    | '/{-$locale}/(root-layout)/terms-of-service/'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug'
    | '/{-$locale}/(centered-layout)/(guest)/sign-in/'
    | '/{-$locale}/(root-layout)/(auth)/admin/'
    | '/{-$locale}/(root-layout)/(auth)/dashboard/'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog'
    | '/{-$locale}/(root-layout)/(auth)/admin/organizations/'
    | '/{-$locale}/(root-layout)/(auth)/admin/organizations/$organizationSlug/'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/members/'
    | '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/$productSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(root-layout)': {
      id: '/{-$locale}/(root-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(centered-layout)': {
      id: '/{-$locale}/(centered-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(root-layout)/': {
      id: '/{-$locale}/(root-layout)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/_api/health/live': {
      id: '/_api/health/live'
      path: '/_api/health/live'
      fullPath: '/_api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(root-layout)/(auth)': {
      id: '/{-$locale}/(root-layout)/(auth)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)': {
      id: '/{-$locale}/(centered-layout)/(guest)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/terms-of-service/': {
      id: '/{-$locale}/(root-layout)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/privacy-policy/': {
      id: '/{-$locale}/(root-layout)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/playground/': {
      id: '/{-$locale}/(root-layout)/playground/'
      path: '/playground'
      fullPath: '/{-$locale}/playground/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/error/': {
      id: '/{-$locale}/(root-layout)/error/'
      path: '/error'
      fullPath: '/{-$locale}/error/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutErrorIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(centered-layout)/accept-invitation/': {
      id: '/{-$locale}/(centered-layout)/accept-invitation/'
      path: '/accept-invitation'
      fullPath: '/{-$locale}/accept-invitation/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutAcceptInvitationIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/dashboard': {
      id: '/{-$locale}/(root-layout)/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthDashboardRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/admin': {
      id: '/{-$locale}/(root-layout)/(auth)/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthAdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/dashboard/': {
      id: '/{-$locale}/(root-layout)/(auth)/dashboard/'
      path: '/'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthDashboardRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/admin/': {
      id: '/{-$locale}/(root-layout)/(auth)/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthAdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthAdminRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/sign-in/': {
      id: '/{-$locale}/(centered-layout)/(guest)/sign-in/'
      path: '/sign-in'
      fullPath: '/{-$locale}/sign-in/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug'
      path: '/org/$organizationSlug'
      fullPath: '/{-$locale}/org/$organizationSlug'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/admin/organizations/': {
      id: '/{-$locale}/(root-layout)/(auth)/admin/organizations/'
      path: '/organizations'
      fullPath: '/{-$locale}/admin/organizations/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthAdminRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog'
      path: '/catalog'
      fullPath: '/{-$locale}/org/$organizationSlug/catalog'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)'
      path: ''
      fullPath: '/{-$locale}/org/$organizationSlug'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/'
      path: '/'
      fullPath: '/{-$locale}/org/$organizationSlug/catalog/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/'
      path: '/'
      fullPath: '/{-$locale}/org/$organizationSlug/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/admin/organizations/$organizationSlug/': {
      id: '/{-$locale}/(root-layout)/(auth)/admin/organizations/$organizationSlug/'
      path: '/organizations/$organizationSlug'
      fullPath: '/{-$locale}/admin/organizations/$organizationSlug/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthAdminRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/$productSlug/': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/catalog/$productSlug/'
      path: '/$productSlug'
      fullPath: '/{-$locale}/org/$organizationSlug/catalog/$productSlug/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/members/': {
      id: '/{-$locale}/(root-layout)/(auth)/org/$organizationSlug/(workspace)/members/'
      path: '/members'
      fullPath: '/{-$locale}/org/$organizationSlug/members/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute
    }
  }
}

interface Char123LocaleChar125centeredLayoutguestRouteRouteChildren {
  Char123LocaleChar125centeredLayoutguestSignInIndexRoute: typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
}

const Char123LocaleChar125centeredLayoutguestRouteRouteChildren: Char123LocaleChar125centeredLayoutguestRouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutguestSignInIndexRoute:
      Char123LocaleChar125centeredLayoutguestSignInIndexRoute,
  }

const Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren =
  Char123LocaleChar125centeredLayoutguestRouteRoute._addFileChildren(
    Char123LocaleChar125centeredLayoutguestRouteRouteChildren,
  )

interface Char123LocaleChar125centeredLayoutRouteRouteChildren {
  Char123LocaleChar125centeredLayoutguestRouteRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren
  Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute: typeof Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute
}

const Char123LocaleChar125centeredLayoutRouteRouteChildren: Char123LocaleChar125centeredLayoutRouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutguestRouteRoute:
      Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren,
    Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute:
      Char123LocaleChar125centeredLayoutAcceptInvitationIndexRoute,
  }

const Char123LocaleChar125centeredLayoutRouteRouteWithChildren =
  Char123LocaleChar125centeredLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125centeredLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthAdminRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthAdminIndexRoute: typeof Char123LocaleChar125rootLayoutauthAdminIndexRoute
  Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute: typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute
  Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute: typeof Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute
}

const Char123LocaleChar125rootLayoutauthAdminRouteRouteChildren: Char123LocaleChar125rootLayoutauthAdminRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthAdminIndexRoute:
      Char123LocaleChar125rootLayoutauthAdminIndexRoute,
    Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute:
      Char123LocaleChar125rootLayoutauthAdminOrganizationsIndexRoute,
    Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute:
      Char123LocaleChar125rootLayoutauthAdminOrganizationsOrganizationSlugIndexRoute,
  }

const Char123LocaleChar125rootLayoutauthAdminRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthAdminRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthAdminRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthDashboardRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthDashboardIndexRoute: typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
}

const Char123LocaleChar125rootLayoutauthDashboardRouteRouteChildren: Char123LocaleChar125rootLayoutauthDashboardRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthDashboardIndexRoute:
      Char123LocaleChar125rootLayoutauthDashboardIndexRoute,
  }

const Char123LocaleChar125rootLayoutauthDashboardRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthDashboardRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthDashboardRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute
}

const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteChildren: Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceIndexRoute,
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceMembersIndexRoute,
  }

const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute
}

const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteChildren: Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogIndexRoute,
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogProductSlugIndexRoute,
  }

const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteWithChildren
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteWithChildren
}

const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteChildren: Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugworkspaceRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugCatalogRouteRouteWithChildren,
  }

const Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthAdminRouteRoute: typeof Char123LocaleChar125rootLayoutauthAdminRouteRouteWithChildren
  Char123LocaleChar125rootLayoutauthDashboardRouteRoute: typeof Char123LocaleChar125rootLayoutauthDashboardRouteRouteWithChildren
  Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute: typeof Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteWithChildren
}

const Char123LocaleChar125rootLayoutauthRouteRouteChildren: Char123LocaleChar125rootLayoutauthRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthAdminRouteRoute:
      Char123LocaleChar125rootLayoutauthAdminRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutauthDashboardRouteRoute:
      Char123LocaleChar125rootLayoutauthDashboardRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRoute:
      Char123LocaleChar125rootLayoutauthOrgOrganizationSlugRouteRouteWithChildren,
  }

const Char123LocaleChar125rootLayoutauthRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthRouteRoute: typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  Char123LocaleChar125rootLayoutIndexRoute: typeof Char123LocaleChar125rootLayoutIndexRoute
  Char123LocaleChar125rootLayoutErrorIndexRoute: typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  Char123LocaleChar125rootLayoutPlaygroundIndexRoute: typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute: typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute: typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
}

const Char123LocaleChar125rootLayoutRouteRouteChildren: Char123LocaleChar125rootLayoutRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthRouteRoute:
      Char123LocaleChar125rootLayoutauthRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutIndexRoute:
      Char123LocaleChar125rootLayoutIndexRoute,
    Char123LocaleChar125rootLayoutErrorIndexRoute:
      Char123LocaleChar125rootLayoutErrorIndexRoute,
    Char123LocaleChar125rootLayoutPlaygroundIndexRoute:
      Char123LocaleChar125rootLayoutPlaygroundIndexRoute,
    Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute:
      Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute,
    Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute:
      Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute,
  }

const Char123LocaleChar125rootLayoutRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125centeredLayoutRouteRoute: typeof Char123LocaleChar125centeredLayoutRouteRouteWithChildren
  Char123LocaleChar125rootLayoutRouteRoute: typeof Char123LocaleChar125rootLayoutRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutRouteRoute:
      Char123LocaleChar125centeredLayoutRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutRouteRoute:
      Char123LocaleChar125rootLayoutRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
