import process from "node:process";

import { createEnv } from "@t3-oss/env-core";
import { isProduction } from "std-env";
import { z } from "zod";

import { betterAuthSecretSchema } from "#@/server/auth-secret";

export const ENV_SERVER = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    VITE_SERVER_URL: isProduction ? z.url() : z.url().default("http://localhost:5000/server"),
    VITE_WEB_URL: isProduction ? z.url() : z.url().default("http://localhost:3000"),
    DATABASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: betterAuthSecretSchema,
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    TRUST_PROXY: z.stringbool().default(false),
    SOURCE_COMMIT: z.string().min(1).default("unknown"), // autogenerated by Coolify, needs to be manually set otherwise
    ENABLE_OPEN_API_DOCS: z.stringbool().default(false),
    IS_BUILD: z.stringbool().default(false) // set to 'true' during build, can be used to conditionally disable features that should only run during runtime and not during build/prerendering
  }
});
